### ISSUE TITLE
Implement validation rules on all the forms

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#33]
Find the data dictionary here 
https://docs.google.com/spreadsheets/d/1AhXXUEwrul1ktQl4cnYFyeBQNTMzl0Rn0sCtLdreUkc/edit?usp=drive_web&ouid=112356819333913957041
Business rules in red text MUST NOT be missed as they are based on more recent user-engagement activities.

**Comment by csamiselo** [comment]
### Task Breakdown for Issue#33

_**A. Client/Facility Information**_

- [ ] Format DD/MMM/YY Field must not allow a date earlier than client's date of birth or any future date - must be pre-filled with today's date.
- [ ] Field to only allow 10 digits in the form 097/095/096/07XXXXXXX

 **_B. Reproductive Health History_** 
- [ ] Field must not allow a date earlier than client's date of birth or any future date

- [ ] If the client does not menstruate the provider must be able to select  Amenorrhea or Menopause (Client's age must be 40 or above for menaupause to be selectable) which are the only possible reasons for any lack of mentruation. If Amenorrhea is selected a field to enter reason must be activated. Example reasons for Amenorrhea).

- [ ] Visit type cannot be "Initial Visit" if any of the choices provided is selected 

- [ ] If Hysterectomy is found,  visit ends.

- [ ] If "Negative" is selected, a field prompting for date should appear (the date when the client tested negtaive)

- [ ] If "No"is selected a field prompting a reason should appear.

**_C. Visit Type_**

- [ ] Referring VIA screening site name must be selected

**_D. HIV Status_**

- [ ] If "Negative" is selected, a field prompting for date should appear (the date when the client tested negtaive)

- [ ] Radiobuttons only get activated if the "Known Positive" radio is selected

- [ ] "On ART" radio must be selected
- [ ]  Format DD/MMM/YY
- [ ]  Format DD/MMM/YY
- [ ] Text box gets activated only if the "Unknown" radiobutton is selected
- [ ] Radiobuttons/choices get activated only if the "Unknown" radiobutton is selectedIf "No" is selected, a field prompting for "Reason" should appear (the reason why PICT was  not offered)
- [ ] Radiobuttons/choices get activated only if the "Unknown" radiobutton is selectedIf "No" is selected, a field prompting for "Reason" should appear (the reason why PICT was  not accepted)
- [ ] Radiobuttons/choices get activated only if the "Unknown" radiobutton is selected and the "Yes" radiobutton" is selected on both "PICT Offered" and "PICT Accepted" fields
- [ ] If "No"is selected a field prompting a reason should appear.

**_E. Physical Exam_**
- [ ] If "Other" is selected a texbox will be invokedIf "Inavsive Cancer" is selected, referal should be the next form with "suspect cancer" pre-population(Text box will only be active when the option "other" is selected)

**_F. Test Results_**
- [ ] Either a "Yes" or "No"  radiobutton must be selected
- [ ]  Text box is activated only if "No"  radiobutton must be selected(If "No" there cant be a VIA result)
- [ ] Text box is activated only when the "No"  radiobutton under "Transformation  zone completely seen" is selected
- [ ] The options are only activated (made selectable) when the "Yes" radiobutton under "Transformation  zone completely seen" is selected
- [ ] The options are only activated (made selectable) when the "Yes" radiobutton under "Transformation  zone completely seen" and then "VIA Positive" under "Screening Results" are selected.
- [ ] If "Yes" client is eligible for Cryotherapy or LEEP
- [ ] If "Yes" client is eligible for Cryotherapy or LEEP
- [ ] If "Yes" client is eligible for LEEP
- [ ] If "Yes" the lesion is not seen entirely. Client is elligible for LEEP
- [ ] If "Yes" client is elligible for LEEP
- [ ] If "Yes" client is elligible for LEEP

**_G. Treatment_**
- [ ] One of the options under "Treatment" must be selected for the these options to be activated (made selectable)

**_I. Prescription(s)_**
- [ ] The checkbox option "Other" must be selected for a text box to be active
- [ ] Checkbox for a particular drug must be selected/checked for the field to be active
- [ ] Checkbox for a particular drug must be selected/checked for the field to be active
- [ ]  Format DD/MMM/YY and can not be in the past
